### PR TITLE
feat: fork is awsom

### PR DESCRIPTION
**Pull request by Guha-Pritam**
# Description

- [x] I have added a folder(Named it as my GitHub user id)
- [x] I have added a Readme.md file inside the folder
- [x] I understand the GitHub Forking Concept fully

### CODE REVIEW

**Comment by atapas** [comment]
@Guha-Pritam follow exact instruction. You need to create a folder with the name same as your GitHub user id. Inside that one Readme.md file. You can write anything in the file.

Also check the checkbox in the PR description when you create it.

**Review by atapas — CHANGES_REQUESTED** [review]
Requesting changes

**Comment by Guha-Pritam** [comment]
okk

**Comment by atapas** [comment]
Hey @Guha-Pritam, please read my comment and follow.

**Comment by Guha-Pritam** [comment]
okk

**Pull request closed without merging**
